require("codemirror/lib/codemirror.js")
require("codemirror/lib/codemirror.css")

require("codemirror/theme/dracula.css")

require("codemirror/mode/css/css.js")
require("codemirror/mode/htmlmixed/htmlmixed.js")
require("codemirror/mode/javascript/javascript.js")
require("codemirror/mode/xml/xml.js")
require("codemirror/addon/fold/brace-fold.js")
require("codemirror/addon/fold/comment-fold.js")
require("codemirror/addon/fold/foldcode.js")
require("codemirror/addon/fold/foldgutter.js")
require("codemirror/addon/fold/foldgutter.css")
require("codemirror/addon/fold/xml-fold.js")
require("codemirror/addon/edit/closebrackets.js")
require("codemirror/addon/edit/closetag.js")
require("codemirror/addon/edit/matchbrackets.js")
require("codemirror/addon/edit/matchtags.js")
require("codemirror/addon/hint/css-hint.js")
require("codemirror/addon/hint/html-hint.js")
require("codemirror/addon/hint/javascript-hint.js")
require("codemirror/addon/hint/show-hint.js")
require("codemirror/addon/hint/show-hint.css")
require("codemirror/addon/selection/active-line.js")
require("codemirror/addon/scroll/simplescrollbars.js")
require("codemirror/addon/scroll/simplescrollbars.css")
require("codemirror/addon/lint/lint.css")
require("codemirror/addon/lint/lint.js")
require("codemirror/addon/lint/css-lint.js")
require("codemirror/addon/lint/javascript-lint.js")
// require("codemirror/addon/lint/html-lint.js")